### ISSUE TITLE
Can't login in nvidia mode

### ISSUE THREAD

**Issue by theLastOfCats** [paltas/FedoraPrime#2]
Login not working correct. After setting nvidia and password type on GDM screen, blank screen and restart GDM.

**Comment by ghost** [comment]
I am not using Fedora anymore, went for openSUSE instead. The problem on switching is unstable is related to newer versions of GDM. You need to boot your computer with intel mode, then switch immediately to nvidia, then it should work. Maybe using lightdm would work.
