### ISSUE TITLE
DNF can sync with copr repo

### ISSUE THREAD

**Issue by theLastOfCats** [paltas/FedoraPrime#3]
Fedora 23. Can sync repo, 'cause can't find folder for 23d.
Link with 22d version, please.

**Comment by ghost** [comment]
Will add it.

**Comment by ghost** [comment]
Build in progress: https://copr.fedorainfracloud.org/coprs/bosim/fedora-prime/build/159668/

**Comment by ghost** [comment]
Didn't work. @DarkRevan Would you be interested in building packages, could transfer the repo to you.
