### ISSUE TITLE
Fedora 23, unable to login in intel mode

### ISSUE THREAD

**Issue by mvoropaiev** [paltas/FedoraPrime#4]
Hello,
after installing on fresh Fedora 23 the following packages

```
akmod-nvidia
kernel-devel
https://copr-be.cloud.fedoraproject.org/results/bosim/fedora-prime/fedora-22-x86_64/00128546-fedora-prime/fedora-prime-0.1-2.fc22.noarch.rpm
```

I was getting "Uh no, something went wrong" message and was thrown back at login screen, after `ctrl+alt+f2` and `fedora-prime-select nvidia` I was able to login normally (nvidia works, yay!), doing `fedora-prime select intel` then login/logout results in the same error message. Maybe there is some workaround for this?

**Comment by mvoropaiev** [comment]
After another fresh re-install and some edits to the `fedora-prime-select` script it seems to work now, maybe the problem was with `/etc/X11/xorg.conf.d/00-avoid-glamor.conf` (installed by `xorg-x11-drv-nvidia`) which needs to be removed for Intel, I'm not sure yet. But anyway, thank you for your work, I was looking for something similar for a long time! :smiley:

**Comment by bosim** [comment]
You are welcome. Could you highlight the modications you did? I am struggling with openSUSE Tumbleweed and GDM currently.

**Comment by mvoropaiev** [comment]
I have reflected the changes I have made for script to work with Fedora 23 in the pr #6
