### ISSUE TITLE
Nvidia gpu showing worse performance than intel

### ISSUE THREAD

**Issue by euoar** [paltas/FedoraPrime#9]
First of all, thanks for the aweasome work. This was something really needed for Fedora users.
I've installed it on Fedora 23, but for some odd reason I'm having worse performance with the nvidia card. Could it be releated to the downgrade of xorg packages to Fedora 22 version? I've tested with glxgears and glmark2, both showing very poor performance for nvidia.

**Comment by mvoropaiev** [comment]
I can confirm it with `glxgears` with downgraded xorg packages and [this xorg.conf](https://github.com/mvoropaiev/FedoraPrime/blob/dev/xorg.conf.template), but `glxspehres64` was still a little faster. Haven't had time to test a real game or benchmark yet.

## Intel

``` sh
vblank_mode=0 glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Visual ID of window: 0xd4
Context is Direct
OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
302.178679 frames/sec - 337.231406 Mpixels/sec
239.686470 frames/sec - 267.490101 Mpixels/sec
226.168591 frames/sec - 252.404147 Mpixels/sec
242.601218 frames/sec - 270.742959 Mpixels/sec
```

``` sh
vblank_mode=0 glxgears 
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
35040 frames in 5.0 seconds = 7007.917 FPS
37615 frames in 5.0 seconds = 7522.859 FPS
36004 frames in 5.0 seconds = 7200.639 FPS
38168 frames in 5.0 seconds = 7633.470 FPS
```

## NVIDIA

``` sh
vblank_mode=0 glxspheres64 
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
Visual ID of window: 0x63
Context is Direct
OpenGL Renderer: GeForce 830M/PCIe/SSE2
290.847202 frames/sec - 324.585477 Mpixels/sec
292.808613 frames/sec - 326.774412 Mpixels/sec
289.209157 frames/sec - 322.757419 Mpixels/sec
299.058824 frames/sec - 333.749648 Mpixels/sec
```

``` sh
vblank_mode=0 glxgears 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
9295 frames in 5.0 seconds = 1858.746 FPS
9945 frames in 5.0 seconds = 1988.083 FPS
9489 frames in 5.0 seconds = 1897.542 FPS
9257 frames in 5.0 seconds = 1851.264 FPS
```

**Comment by euoar** [comment]
It looks like the correct command to check the performance with the nvidia card is: __GL_SYNC_TO_VBLANK=0 glxgears

Using it, now I can get better results with the nvidia card than with the intel one:
(GForce GT 630M)

__GL_SYNC_TO_VBLANK=0 glxgears
42480 frames in 5.0 seconds = 8495.889 FPS
43673 frames in 5.0 seconds = 8734.485 FPS
38686 frames in 5.0 seconds = 7737.146 FPS
39862 frames in 5.0 seconds = 7972.381 FPS
48551 frames in 5.0 seconds = 9710.062 FPS
23412 frames in 5.0 seconds = 4682.153 FPS
36838 frames in 5.0 seconds = 7367.489 FPS
49467 frames in 5.0 seconds = 9893.324 FPS
49561 frames in 5.0 seconds = 9912.016 FPS
49439 frames in 5.0 seconds = 9887.734 FPS

With the intel card it's usually between 32000 - 37000 frames in 5.0 seconds.

**Comment by mvoropaiev** [comment]
@euoar good find!
